### ISSUE TITLE
discord.py 2.0 checklist

### ISSUE THREAD

**Issue by ultrabear** [Sonnet-Discord/sonnet-py#73]
This is a tracking issue to track the changes made in sonnet core to accommodate discord.py 2.0 when it releases

**Comment by ultrabear** [comment]
- [ ] Sonnet Deprecations
  - [ ] Remove deprecated db_hlapi calls
  - [ ] Remove deprecated lib_loaders functions
  - [ ] Remove deprecated lib_parsers functions
- [ ] dpy Breaking Changes
  - [ ] Asset management changed

**Comment by ultrabear** [comment]
Current status: dpy is gone, gonna wait on pycord and see if they manage to pull through a 2.0 release

**Comment by ultrabear** [comment]
Update: pycord 2.0 is planned to release sometime in january
sonnet 2.0 will no longer remove deprecated endpoints, and lib_compatibility will accommodate 1.0 code
Sonnet 2.0 will not remove lib_compatibility, but will require pycord 2.0 for its own internal functions, including rewriting lib_compatibility to be in 2.0 mode

**Comment by ultrabear** [comment]
any code written in dpy 1.0 that does not use lib_compatibility, or code that uses removed endpoints, will have breaking changes that are beyond the scope of sonnet

**Comment by ultrabear** [comment]
for now, dev-2.0 should just be removed, it is out of date and not representative of what 2.0 will look like

**Comment by ultrabear** [comment]
pycord 2.0 release delayed, nextcord apparently releasing a faster v3 library that mainly does internal changes
dont know what will work well yet, dont know why they called it v3, more information needed

**Comment by ultrabear** [comment]
(do not go all in on pycord/nextcord until more information is available)

**Comment by ultrabear** [comment]
nc2.0 is out, waiting on a dpy2 release to see if its better, whichever library is picked will have long term implications on overall usability

**Comment by ultrabear** [comment]
dropping pycord entirely as a candidate

**Comment by ultrabear** [comment]
discord.py 2.0 has released!
currently the only blocking change needed to be made is adding LeXdPyK 1.5 with undefined dlib exec order, as bots will be rebooted adding this long standing unimplemented feature is important to do now

**Comment by ultrabear** [comment]
LeXdPyK 1.5 added as of 0cbea314052bb4255d48e490bb285a7904d9188a

work will begin under dev-2.0

**Comment by ultrabear** [comment]
work is completed for MVP 2.0 integration (general correctness and thread logging), dev-2.0 will merge with dev-unstable on friday
